# Generated by Django 4.1.4 on 2023-01-03 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('Answer_Id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=500)),
                ('CreationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_Id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=2000)),
                ('CreationDate', models.DateTimeField()),
                ('Answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
            ],
        ),
    ]
