# Generated by Django 4.1.4 on 2023-01-03 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=15, null=True), size=None),
        ),
    ]
