# Generated by Django 4.1.4 on 2023-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
